/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ciarpvisual;

import Excel.GeneracionCuadros;
import RTF.GeneracionActas;
import RTF.GeneracionCartas;
import RTF.GeneracionResoluciones;
import com.lowagie.text.DocumentException;
import java.awt.Color;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author rjulio, rramos, kdelosreyes
 */
public class VistaPrincipal extends javax.swing.JFrame {
    private int x, y;
    Calendar jc;
    int anioAct;
    
    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        
        estadoSemestre(false);
        jc = Calendar.getInstance();
        anioAct = jc.get(Calendar.YEAR);
        System.out.println("jc.getTime();-->"+anioAct);
        EstablecerAniosCartas();
        cbAnioCartas.setSelectedItem(anioAct);
        if(cbAnioCartas.getSelectedItem().equals("Seleccionar")){
            lblAnio.setText("AÑO");
        } else{
            lblAnio.setText(""+anioAct);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Actas = new javax.swing.JPanel();
        lblsemestre = new javax.swing.JLabel();
        cbSemestre = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        btnSelectArchivo1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnSelectArchivo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtURL = new javax.swing.JTextField();
        lblTid1 = new javax.swing.JLabel();
        cbTid = new javax.swing.JComboBox();
        lblTid = new javax.swing.JLabel();
        Cuadros = new javax.swing.JPanel();
        lbldocentesTitle = new javax.swing.JLabel();
        txtURLDocentes = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        btnSelectArchivoDocentes = new javax.swing.JButton();
        lblPuntosTitle1 = new javax.swing.JLabel();
        txtURLPuntos = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        btnGenerarCuaros = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnSelectArchivoPuntos = new javax.swing.JButton();
        lblsemestre1 = new javax.swing.JLabel();
        cbAnio = new javax.swing.JComboBox();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        Cartas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtOrdendeldia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtConsecutivo = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel9 = new javax.swing.JPanel();
        btnGenerarCartas = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        btnSelectArchivoDocentes1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblAnio = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbAnioCartas = new javax.swing.JComboBox();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/minimizar.png"))); // NOI18N
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 5, -1, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/cerrar_1.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 5, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Generación documentos CIARP");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 40));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(26, 82, 118));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        Actas.setBackground(new java.awt.Color(255, 255, 255));
        Actas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblsemestre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblsemestre.setForeground(new java.awt.Color(26, 82, 118));
        lblsemestre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblsemestre.setText("Semestre");
        Actas.add(lblsemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 60, -1));

        cbSemestre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbSemestre.setForeground(new java.awt.Color(31, 97, 141));
        cbSemestre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Primer Semestre", "Segundo Semestre" }));
        cbSemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSemestreActionPerformed(evt);
            }
        });
        Actas.add(cbSemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 180, 30));

        jPanel5.setBackground(new java.awt.Color(26, 82, 118));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSelectArchivo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSelectArchivo1.setForeground(new java.awt.Color(255, 255, 255));
        btnSelectArchivo1.setText("Generar");
        btnSelectArchivo1.setBorderPainted(false);
        btnSelectArchivo1.setContentAreaFilled(false);
        btnSelectArchivo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSelectArchivo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSelectArchivo1MouseExited(evt);
            }
        });
        btnSelectArchivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectArchivo1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnSelectArchivo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        Actas.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 100, 30));

        jPanel4.setBackground(new java.awt.Color(26, 82, 118));

        btnSelectArchivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSelectArchivo.setForeground(new java.awt.Color(255, 255, 255));
        btnSelectArchivo.setText("Seleccionar Archivo");
        btnSelectArchivo.setBorderPainted(false);
        btnSelectArchivo.setContentAreaFilled(false);
        btnSelectArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSelectArchivoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSelectArchivoMouseExited(evt);
            }
        });
        btnSelectArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnSelectArchivo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnSelectArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Actas.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, 30));

        jSeparator1.setBackground(new java.awt.Color(59, 123, 50));
        Actas.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 350, -1));

        txtURL.setEditable(false);
        txtURL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtURL.setCaretColor(new java.awt.Color(26, 82, 118));
        txtURL.setSelectionColor(new java.awt.Color(26, 82, 118));
        Actas.add(txtURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 350, 30));

        lblTid1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTid1.setForeground(new java.awt.Color(26, 82, 118));
        lblTid1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTid1.setText("Generar");
        Actas.add(lblTid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 60, -1));

        cbTid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbTid.setForeground(new java.awt.Color(31, 97, 141));
        cbTid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Acta", "Resolucion" }));
        cbTid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTidActionPerformed(evt);
            }
        });
        Actas.add(cbTid, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 210, 30));

        lblTid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTid.setForeground(new java.awt.Color(26, 82, 118));
        lblTid.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTid.setText("Archivo");
        Actas.add(lblTid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 60, -1));

        jTabbedPane1.addTab("Actas y Resoluciones", Actas);

        Cuadros.setBackground(new java.awt.Color(255, 255, 255));
        Cuadros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbldocentesTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbldocentesTitle.setForeground(new java.awt.Color(26, 82, 118));
        lbldocentesTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbldocentesTitle.setText("Docentes");
        Cuadros.add(lbldocentesTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 60, -1));

        txtURLDocentes.setEditable(false);
        txtURLDocentes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtURLDocentes.setCaretColor(new java.awt.Color(26, 82, 118));
        txtURLDocentes.setSelectionColor(new java.awt.Color(26, 82, 118));
        Cuadros.add(txtURLDocentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 350, 30));

        jSeparator2.setBackground(new java.awt.Color(59, 123, 50));
        Cuadros.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 350, 10));

        jPanel6.setBackground(new java.awt.Color(26, 82, 118));

        btnSelectArchivoDocentes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSelectArchivoDocentes.setForeground(new java.awt.Color(255, 255, 255));
        btnSelectArchivoDocentes.setText("Cargar Archivo");
        btnSelectArchivoDocentes.setBorderPainted(false);
        btnSelectArchivoDocentes.setContentAreaFilled(false);
        btnSelectArchivoDocentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSelectArchivoDocentesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSelectArchivoDocentesMouseExited(evt);
            }
        });
        btnSelectArchivoDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectArchivoDocentesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnSelectArchivoDocentes)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnSelectArchivoDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Cuadros.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 130, 30));

        lblPuntosTitle1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPuntosTitle1.setForeground(new java.awt.Color(26, 82, 118));
        lblPuntosTitle1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPuntosTitle1.setText("Puntos Todos");
        Cuadros.add(lblPuntosTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 60, -1));

        txtURLPuntos.setEditable(false);
        txtURLPuntos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtURLPuntos.setCaretColor(new java.awt.Color(26, 82, 118));
        txtURLPuntos.setSelectionColor(new java.awt.Color(26, 82, 118));
        Cuadros.add(txtURLPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 350, 30));

        jSeparator3.setBackground(new java.awt.Color(59, 123, 50));
        Cuadros.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 350, 10));

        jPanel8.setBackground(new java.awt.Color(26, 82, 118));

        btnGenerarCuaros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGenerarCuaros.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarCuaros.setText("Generar");
        btnGenerarCuaros.setBorderPainted(false);
        btnGenerarCuaros.setContentAreaFilled(false);
        btnGenerarCuaros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGenerarCuarosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGenerarCuarosMouseExited(evt);
            }
        });
        btnGenerarCuaros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarCuarosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnGenerarCuaros)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnGenerarCuaros, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Cuadros.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 130, 30));

        jPanel7.setBackground(new java.awt.Color(26, 82, 118));

        btnSelectArchivoPuntos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSelectArchivoPuntos.setForeground(new java.awt.Color(255, 255, 255));
        btnSelectArchivoPuntos.setText("Cargar Archivo");
        btnSelectArchivoPuntos.setBorderPainted(false);
        btnSelectArchivoPuntos.setContentAreaFilled(false);
        btnSelectArchivoPuntos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSelectArchivoPuntosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSelectArchivoPuntosMouseExited(evt);
            }
        });
        btnSelectArchivoPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectArchivoPuntosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnSelectArchivoPuntos)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnSelectArchivoPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Cuadros.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 130, 30));

        lblsemestre1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblsemestre1.setForeground(new java.awt.Color(26, 82, 118));
        lblsemestre1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblsemestre1.setText("Año");
        Cuadros.add(lblsemestre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, -1));

        cbAnio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbAnio.setForeground(new java.awt.Color(31, 97, 141));
        cbAnio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "2025", "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017" }));
        cbAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAnioActionPerformed(evt);
            }
        });
        Cuadros.add(cbAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 180, 30));
        Cuadros.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, -20, -1, -1));

        jTabbedPane1.addTab("Cuadros", Cuadros);

        Cartas.setBackground(new java.awt.Color(255, 255, 255));
        Cartas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(26, 82, 118));
        jLabel2.setText("Archivo:");
        Cartas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(59, 123, 50));
        jSeparator4.setAlignmentX(0.3F);
        jSeparator4.setAlignmentY(0.3F);
        Cartas.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 134, 338, -1));

        txtOrdendeldia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrdendeldiaActionPerformed(evt);
            }
        });
        Cartas.add(txtOrdendeldia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 338, 34));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(26, 82, 118));
        jLabel3.setText("-");
        Cartas.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 60, 10, -1));

        txtConsecutivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsecutivoActionPerformed(evt);
            }
        });
        Cartas.add(txtConsecutivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 57, 40, 20));

        jSeparator5.setBackground(new java.awt.Color(59, 123, 50));
        Cartas.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 40, 10));

        jPanel9.setBackground(new java.awt.Color(26, 82, 118));

        btnGenerarCartas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGenerarCartas.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarCartas.setText("Generar");
        btnGenerarCartas.setBorderPainted(false);
        btnGenerarCartas.setContentAreaFilled(false);
        btnGenerarCartas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGenerarCartasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGenerarCartasMouseExited(evt);
            }
        });
        btnGenerarCartas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarCartasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(btnGenerarCartas)
                .addGap(22, 22, 22))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGenerarCartas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Cartas.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        jPanel11.setBackground(new java.awt.Color(26, 82, 118));

        btnSelectArchivoDocentes1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSelectArchivoDocentes1.setForeground(new java.awt.Color(255, 255, 255));
        btnSelectArchivoDocentes1.setText("Cargar Archivo");
        btnSelectArchivoDocentes1.setBorderPainted(false);
        btnSelectArchivoDocentes1.setContentAreaFilled(false);
        btnSelectArchivoDocentes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSelectArchivoDocentes1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSelectArchivoDocentes1MouseExited(evt);
            }
        });
        btnSelectArchivoDocentes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectArchivoDocentes1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnSelectArchivoDocentes1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnSelectArchivoDocentes1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Cartas.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 130, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(26, 82, 118));
        jLabel4.setText("Año:");
        Cartas.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(26, 82, 118));
        jLabel5.setText("CIARP-");
        Cartas.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        lblAnio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAnio.setForeground(new java.awt.Color(26, 82, 118));
        lblAnio.setText("AÑO");
        Cartas.add(lblAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 60, 50, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(26, 82, 118));
        jLabel7.setText("Consecutivo:");
        Cartas.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        cbAnioCartas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbAnioCartas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAnioCartasActionPerformed(evt);
            }
        });
        Cartas.add(cbAnioCartas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 80, 30));

        jTabbedPane1.addTab("Cartas", null, Cartas, "");

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 40, 605, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void cbTidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTidActionPerformed
        estadoSemestre(cbTid.getSelectedItem().equals("Resolucion"));
    }//GEN-LAST:event_cbTidActionPerformed

    private void btnSelectArchivoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectArchivoMouseEntered
        jPanel4.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_btnSelectArchivoMouseEntered

    private void btnSelectArchivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectArchivoMouseExited
        jPanel4.setBackground(new Color(26, 82, 118));
    }//GEN-LAST:event_btnSelectArchivoMouseExited

    private void btnSelectArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectArchivoActionPerformed
        txtURL.setText(Expresiones.seleccionarArchivos(false, "C:/CIARP/"));
        //System.out.println("txtURL-->"+txtURL.getText());
    }//GEN-LAST:event_btnSelectArchivoActionPerformed

    private void btnSelectArchivo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectArchivo1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectArchivo1MouseEntered

    private void btnSelectArchivo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectArchivo1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectArchivo1MouseExited

    private void btnSelectArchivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectArchivo1ActionPerformed
        try {
            Generar();
        }catch(DocumentException e){
          
        }catch(IOException e){
            
        }
    }//GEN-LAST:event_btnSelectArchivo1ActionPerformed

    private void cbSemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSemestreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSemestreActionPerformed

    private void btnSelectArchivoDocentesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectArchivoDocentesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectArchivoDocentesMouseEntered

    private void btnSelectArchivoDocentesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectArchivoDocentesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectArchivoDocentesMouseExited

    private void btnSelectArchivoDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectArchivoDocentesActionPerformed
        txtURLDocentes.setText(Expresiones.seleccionarArchivos(false, "C:/CIARP/"));
        
    }//GEN-LAST:event_btnSelectArchivoDocentesActionPerformed

    private void btnSelectArchivoPuntosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectArchivoPuntosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectArchivoPuntosMouseEntered

    private void btnSelectArchivoPuntosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectArchivoPuntosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectArchivoPuntosMouseExited

    private void btnSelectArchivoPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectArchivoPuntosActionPerformed
        txtURLPuntos.setText(Expresiones.seleccionarArchivos(false, "C:/CIARP/"));
    }//GEN-LAST:event_btnSelectArchivoPuntosActionPerformed

    private void btnGenerarCuarosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarCuarosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarCuarosMouseEntered

    private void btnGenerarCuarosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarCuarosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarCuarosMouseExited

    private void btnGenerarCuarosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarCuarosActionPerformed
        try {
            GenerarCuadros();
            JOptionPane.showMessageDialog(null, "Inició la generación de cuadros");
        }catch(DocumentException e){
          
        }catch(IOException e){
            
        }
    }//GEN-LAST:event_btnGenerarCuarosActionPerformed

    private void cbAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAnioActionPerformed
        
    }//GEN-LAST:event_cbAnioActionPerformed

    private void txtOrdendeldiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrdendeldiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrdendeldiaActionPerformed

    private void txtConsecutivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsecutivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsecutivoActionPerformed

    private void btnGenerarCartasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarCartasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarCartasMouseEntered

    private void btnGenerarCartasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarCartasMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarCartasMouseExited

    private void btnGenerarCartasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarCartasActionPerformed
        try {
            GenerarCartas();
        }catch(DocumentException e){
          
        }catch(IOException e){
            
        } catch (Exception ex) {
            Logger.getLogger(VistaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGenerarCartasActionPerformed

    private void btnSelectArchivoDocentes1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectArchivoDocentes1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectArchivoDocentes1MouseEntered

    private void btnSelectArchivoDocentes1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectArchivoDocentes1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectArchivoDocentes1MouseExited

    private void btnSelectArchivoDocentes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectArchivoDocentes1ActionPerformed
       txtOrdendeldia.setText(Expresiones.seleccionarArchivos(false, "C:/CIARP/"));
    }//GEN-LAST:event_btnSelectArchivoDocentes1ActionPerformed

    private void cbAnioCartasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAnioCartasActionPerformed
        if(cbAnioCartas.getItemCount()>0){
            lblAnio.setText(""+cbAnioCartas.getSelectedItem());
        }
    }//GEN-LAST:event_cbAnioCartasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Actas;
    private javax.swing.JPanel Cartas;
    private javax.swing.JPanel Cuadros;
    public javax.swing.JButton btnGenerarCartas;
    public javax.swing.JButton btnGenerarCuaros;
    public javax.swing.JButton btnSelectArchivo;
    public javax.swing.JButton btnSelectArchivo1;
    public javax.swing.JButton btnSelectArchivoDocentes;
    public javax.swing.JButton btnSelectArchivoDocentes1;
    public javax.swing.JButton btnSelectArchivoPuntos;
    public javax.swing.JComboBox cbAnio;
    private javax.swing.JComboBox cbAnioCartas;
    public javax.swing.JComboBox cbSemestre;
    public javax.swing.JComboBox cbTid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblPuntosTitle1;
    private javax.swing.JLabel lblTid;
    private javax.swing.JLabel lblTid1;
    private javax.swing.JLabel lbldocentesTitle;
    private javax.swing.JLabel lblsemestre;
    private javax.swing.JLabel lblsemestre1;
    private javax.swing.JTextField txtConsecutivo;
    private javax.swing.JTextField txtOrdendeldia;
    public javax.swing.JTextField txtURL;
    public javax.swing.JTextField txtURLDocentes;
    public javax.swing.JTextField txtURLPuntos;
    // End of variables declaration//GEN-END:variables

    private void Generar() throws DocumentException, IOException {
        String tipo = cbTid.getSelectedItem().toString();
        String ruta = txtURL.getText().trim();
        
        if(tipo.equals("Acta")){
           GeneracionActas gen = new GeneracionActas();
            Map<String, String> respuestaerr = gen.GenerarActas(ruta);
            
            if(respuestaerr.get("ESTADO").equals("ERROR")){
            JOptionPane.showMessageDialog(this, "posible error de digitación "+Utilidades.Utilidades.decodificarElemento(respuestaerr.get("MENSAJE"))+
                    "\nPara el docente: "+Utilidades.Utilidades.decodificarElemento(respuestaerr.get("LINEA_ERROR_DOCENTE"))+
                    "\nTipo de producto: "+Utilidades.Utilidades.decodificarElemento(respuestaerr.get("LINEA_ERROR_PRODUCTO"))+"\nEn el producto: "+Utilidades.Utilidades.decodificarElemento(respuestaerr.get("NOMBRE_PRODUCTO")),
                    respuestaerr.get("ESTADO"), JOptionPane.DEFAULT_OPTION);
            }else if(respuestaerr.get("ESTADO").equals("OK")){
                JOptionPane.showMessageDialog(this,"EJECUCION EXITOSA", respuestaerr.get("ESTADO"), JOptionPane.DEFAULT_OPTION);
            }
        } else if(tipo.equals("Resolucion")){
            String semestre = ""+cbSemestre.getSelectedItem();
            if(semestre.equals("Seleccionar")){
                JOptionPane.showMessageDialog(this, "Por favor seleccione un semestre");
                return;
            }
            GeneracionResoluciones gen = new GeneracionResoluciones();
            Map<String, String> respuesta = gen.CrearResoluciones(ruta, semestre);
            
            if(respuesta.get("ESTADO").equals("ERROR")){
            JOptionPane.showMessageDialog(this, "posible error de digitación "+Utilidades.Utilidades.decodificarElemento(respuesta.get("MENSAJE"))+
                    "\nPara el docente: "+Utilidades.Utilidades.decodificarElemento(respuesta.get("LINEA_ERROR_DOCENTE"))+
                    "\nTipo de producto: "+Utilidades.Utilidades.decodificarElemento(respuesta.get("LINEA_ERROR_PRODUCTO"))+"\nEn el producto: "+Utilidades.Utilidades.decodificarElemento(respuesta.get("NOMBRE_PRODUCTO")),
                    respuesta.get("ESTADO"), JOptionPane.DEFAULT_OPTION);
            }else if(respuesta.get("ESTADO").equals("OK")){
                JOptionPane.showMessageDialog(this,"EJECUCION EXITOSA", respuesta.get("ESTADO"), JOptionPane.DEFAULT_OPTION);
            }
           
        } 
    }

    private void estadoSemestre(boolean b) {
        lblsemestre.setVisible(b);
        cbSemestre.setVisible(b);
    }

    private void GenerarCuadros()throws DocumentException, IOException {
        String anio = cbAnio.getSelectedItem().toString();
        String rutaDocentes = txtURLDocentes.getText().trim();
        String rutaPuntos = txtURLPuntos.getText().trim();
        
        
        if(anio.equals("Seleccionar")){
            JOptionPane.showMessageDialog(this, "Por favor seleccione un año.");
            return;
        }
        
        if(rutaDocentes.equals("")){
            JOptionPane.showMessageDialog(this, "Por favor seleccione el archivo de los docentes de planta.");
            return;
        }
        
        if(rutaPuntos.equals("")){
            JOptionPane.showMessageDialog(this, "Por favor seleccione el archivo de puntos todos.");
            return;
        }
        
        GeneracionCuadros gen = new GeneracionCuadros();
        Map<String, String> respuesta = gen.GenerarCuadros(anio, rutaDocentes, rutaPuntos);
        if(respuesta.get("ESTADO").equals("ERROR")){
        JOptionPane.showMessageDialog(this, "posible error de digitación "+Utilidades.Utilidades.decodificarElemento(respuesta.get("MENSAJE"))+"\nPara el docente: "+Utilidades.Utilidades.decodificarElemento(respuesta.get("LINEA_ERROR_DOCENTE"))+
                "\nTipo de producto: "+Utilidades.Utilidades.decodificarElemento(respuesta.get("LINEA_ERROR_PRODUCTO"))+
                "\nEn el producto: "+Utilidades.Utilidades.decodificarElemento(respuesta.get("NOMBRE_SOLICITUD")), respuesta.get("ESTADO"), JOptionPane.DEFAULT_OPTION);
        }else if(respuesta.get("ESTADO").equals("OK")){
            JOptionPane.showMessageDialog(this, "EJECUCION EXITOSA", respuesta.get("ESTADO"), JOptionPane.DEFAULT_OPTION);
        }
    }

    private void GenerarCartas() throws DocumentException, IOException, Exception {
       String consecutivo = txtConsecutivo.getText().trim();
       String anio = lblAnio.getText().trim();
       String rutaOrden = txtOrdendeldia.getText().trim();
       if(rutaOrden.equals("")){
            JOptionPane.showMessageDialog(this, "Por favor seleccione el archivo de orden del día.");
            return;
        }
       GeneracionCartas gen = new GeneracionCartas();
       Map<String, String> respuesta = gen.Generarcartas(rutaOrden, consecutivo, anio);
       if(respuesta.get("ESTADO").equals("ERROR")){
       JOptionPane.showMessageDialog(this, "Posible error de digitación "+Utilidades.Utilidades.decodificarElemento(respuesta.get("MENSAJE"))
               +"\nPara el docente: "+Utilidades.Utilidades.decodificarElemento(respuesta.get("LINEA_ERROR_DOCENTE"))+
               "\nTipo de producto: "+Utilidades.Utilidades.decodificarElemento(respuesta.get("LINEA_ERROR_PRODUCTO"))+"\nEn el producto: "+Utilidades.Utilidades.decodificarElemento(respuesta.get("NOMBRE_PRODUCTO")), respuesta.get("ESTADO"),JOptionPane.DEFAULT_OPTION);
        }else if(respuesta.get("ESTADO").equals("OK")){
            JOptionPane.showMessageDialog(this, "EJECUCION EXITOSA", respuesta.get("ESTADO"),JOptionPane.DEFAULT_OPTION);
        }
    }   
    
    //<editor-fold defaultstate="collapsed" desc="COMBO ANIOS">
        
    private void EstablecerAniosCartas() {
        
        cbAnioCartas.removeAllItems();
        cbAnioCartas.addItem("Seleccionar");
        for(int i = anioAct-2; i <= anioAct+4; i++){
            cbAnioCartas.addItem(""+i);
        }
        
    }
    
    
    //</editor-fold>
}
